# Supabase Configuration
supabase.url=https://lpzzamfswasnakegsube.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwenphbWZzd2FzbmFrZWdzdWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1NjU4MTMsImV4cCI6MjA4OTE0MTgxM30.5JlxpEsQTxuR21BTWWAO87kIL00MhuYur30MPZEMEQ0