package com.example.mykeyboard.personal

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

class PersonalJarvisIsolationGuardrailsTest {
    @Test
    fun personalJarvisIsIsolatedAndRemovable() {
        val manifest = sourceFile("app/src/main/AndroidManifest.xml").readText()
        val buildGradle = sourceFile("app/build.gradle.kts").readText()
        val keyboardService = sourceFile("app/src/main/java/com/example/mykeyboard/KeyboardService.kt").readText()

        assertTrue(buildGradle.contains("PERSONAL_JARVIS_ENABLED"))
        assertTrue(manifest.contains("android:name=\".AritenisApplication\""))
        assertTrue(manifest.contains(".personal.JarvisNotificationListenerService"))
        assertTrue(manifest.contains("android.permission.BIND_NOTIFICATION_LISTENER_SERVICE"))
        assertTrue(manifest.contains(".personal.JarvisReminderReceiver"))
        assertFalse(keyboardService.contains("JarvisNotificationListenerService"))
        assertFalse(keyboardService.contains("JarvisReleaseDetector"))
    }

    @Test
    fun personalJarvisDoesNotUseCloudOrAccessibilityControl() {
        val personalSources = sourceFiles("app/src/main/java/com/example/mykeyboard/personal")
            .joinToString("\n") { it.readText() }
        val manifest = sourceFile("app/src/main/AndroidManifest.xml").readText()

        assertFalse(personalSources.contains("Supabase"))
        assertFalse(personalSources.contains("http://"))
        assertFalse(personalSources.contains("https://api."))
        assertFalse(personalSources.contains("https://supabase"))
        assertFalse(personalSources.contains("https://openai"))
        assertFalse(personalSources.contains("AccessibilityService"))
        assertFalse(manifest.contains("android.permission.BIND_ACCESSIBILITY_SERVICE"))
    }

    @Test
    fun personalJarvisDelegatesQuestionsToFounderBrainOnly() {
        val connector = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisBrainConnector.kt").readText()
        val listener = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisNotificationListenerService.kt").readText()
        val runtime = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisBrainRuntime.kt").readText()
        val personalSources = sourceFiles("app/src/main/java/com/example/mykeyboard/personal")
            .joinToString("\n") { it.readText() }

        assertTrue(connector.contains("founderBrainQuestionEndpoint()"))
        assertTrue(connector.contains("Authorization"))
        assertTrue(connector.contains("voiceSummary"))
        assertTrue(connector.contains("executionIntent"))
        assertTrue(connector.contains("fallbackMessage"))
        assertTrue(connector.contains("fallbackAnswer"))
        assertTrue(connector.contains("configurationIssue"))
        assertTrue(connector.contains("MAX_RETRY_ATTEMPTS"))
        assertTrue(connector.contains("retryDelayMs"))
        assertTrue(runtime.contains("JarvisBrainConnector().also"))
        assertTrue(listener.contains("JarvisBrainRuntime.connector(this)"))
        assertTrue(listener.contains("JarvisQuestionDetector.extractQuestion"))
        assertTrue(listener.contains("JarvisBrainSpeechPolicy.speechFor(answer)"))
        assertTrue(listener.contains("speaker.speak(spoken)"))
        assertTrue(listener.contains("JarvisBrainSpeechPolicy.safeFallback()"))
        assertFalse(listener.contains("answer.voiceSummary.ifBlank { answer.summary }"))
        assertFalse(listener.contains("speaker.speak(reason)"))
        assertFalse(listener.contains("Sir, checking the Founder Brain."))
        assertFalse(listener.contains("brainConnector.shutdown()"))
        assertFalse(personalSources.contains("Founder Brain is not connected"))
        assertFalse(personalSources.contains("Founder Brain is unavailable right now."))
        assertFalse(personalSources.contains("Founder Brain responded, but the voice answer was empty."))
        assertFalse(personalSources.contains("Founder Brain API URL is missing from this APK build."))
        assertFalse(personalSources.contains("Founder Brain token is missing from this APK build."))
        assertFalse(personalSources.contains("Founder Brain rejected the API token."))
        assertFalse(personalSources.contains("routeConfidence"))
        assertFalse(personalSources.contains("routeMessageWithAi"))
        assertFalse(personalSources.contains("answerFounderBrainQuestion"))
        assertFalse(personalSources.contains(".brain_state.json"))
        assertFalse(personalSources.contains("rawReasoning"))
    }

    @Test
    fun wakeWordServiceKeepsActiveConversationAfterFounderBrainVoiceSummary() {
        val wakeService = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisWakeWordService.kt").readText()
        val connector = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisBrainConnector.kt").readText()
        val speechPolicy = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisBrainSpeechPolicy.kt").readText()
        val speaker = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisSpeaker.kt").readText()

        assertTrue(wakeService.contains("JarvisConversationState.IDLE"))
        assertTrue(wakeService.contains("JarvisConversationState.WAKE_CONFIRMED"))
        assertTrue(wakeService.contains("JarvisConversationState.COMMAND_CAPTURE"))
        assertTrue(wakeService.contains("JarvisConversationState.PROCESSING"))
        assertTrue(wakeService.contains("JarvisConversationState.SPEAKING"))
        assertTrue(wakeService.contains("JarvisConversationState.RETURN_TO_IDLE"))
        assertTrue(wakeService.contains("transitionTo"))
        assertTrue(wakeService.contains("currentState()"))
        assertTrue(wakeService.contains("JarvisWakeWordEngine.containsWakeWord"))
        assertTrue(wakeService.contains("private object JarvisWakeWordEngine"))
        assertTrue(wakeService.contains("JarvisPorcupineWakeEngine"))
        assertTrue(wakeService.contains("JarvisVoskWakeEngine"))
        assertTrue(wakeService.contains("porcupineWakeEngine?.start() == true"))
        assertTrue(wakeService.contains("voskWakeEngine?.start() == true"))
        assertTrue(wakeService.contains("porcupineWakeEngine?.stop(\"wake accepted before acknowledgment\")"))
        assertTrue(wakeService.contains("voskWakeEngine?.stop(\"wake accepted before acknowledgment\")"))
        assertTrue(wakeService.contains("porcupineWakeEngine?.shutdown()"))
        assertTrue(wakeService.contains("voskWakeEngine?.shutdown()"))
        assertTrue(wakeService.contains("JarvisVoiceSession"))
        assertTrue(wakeService.contains("activeSession != null"))
        assertTrue(wakeService.contains("WAKE_DEBOUNCE_MS"))
        assertTrue(wakeService.contains("NO_MATCH_RESTART_DELAY_MS"))
        assertTrue(wakeService.contains("COMMAND_MAX_RESULTS"))
        assertTrue(wakeService.contains("COMMAND_MINIMUM_INPUT_MS"))
        assertTrue(wakeService.contains("COMMAND_COMPLETE_SILENCE_MS"))
        assertTrue(wakeService.contains("COMMAND_POSSIBLY_COMPLETE_SILENCE_MS"))
        assertTrue(wakeService.contains("handleCommandResults"))
        assertTrue(wakeService.contains("askFounderBrain(session, question)"))
        assertTrue(wakeService.contains("sessionId = session.id"))
        assertTrue(wakeService.contains("JarvisBrainRuntime.connector(this)"))
        assertFalse(wakeService.contains("!connector.isReady()"))
        assertTrue(wakeService.contains("activeSession?.id != session.id"))
        assertTrue(wakeService.contains("releaseSession("))
        assertTrue(wakeService.contains("JarvisBrainSpeechPolicy.speechFor(answer)"))
        assertTrue(wakeService.contains("speakAndContinueConversation(speech"))
        assertTrue(wakeService.contains(".setSilent(true)"))
        assertFalse(wakeService.contains("AudioFocusRequest"))
        assertFalse(wakeService.contains("requestAudioFocus()"))
        assertFalse(wakeService.contains("abandonAudioFocus()"))
        assertFalse(wakeService.contains("ListeningMode"))
        assertFalse(wakeService.contains("AudioState"))
        assertFalse(wakeService.contains("private var listening = false"))
        assertFalse(wakeService.contains("listening = false"))
        assertFalse(wakeService.contains("listening = true"))
        val wakeDetection = wakeService.substringAfter("private fun handleWakeWordDetected")
            .substringBefore("private fun handleCommandResults")
        assertTrue(wakeDetection.contains("cancelRecognizerForTransition"))
        assertTrue(wakeDetection.contains("JarvisConversationState.WAKE_CONFIRMED"))
        assertTrue(wakeDetection.contains("JarvisConversationState.COMMAND_CAPTURE"))
        assertTrue(wakeDetection.contains("speaker?.speak(JarvisWakeResponseGate.RESPONSE_TEXT, afterAcknowledgement)"))
        assertTrue(wakeDetection.contains("scheduleCommandStart()"))
        assertFalse(wakeService.contains("private fun restartListening"))
        assertTrue(wakeService.contains("scheduleWakeRestart"))
        assertTrue(wakeService.contains("scheduleCommandStart"))
        assertTrue(wakeService.contains("COMMAND_LISTEN_DELAY_MS"))
        assertTrue(wakeService.contains("RESTART_DELAY_MS"))
        assertTrue(wakeService.contains("SpeechRecognizer.ERROR_NO_MATCH -> NO_MATCH_RESTART_DELAY_MS"))
        assertTrue(wakeService.contains("Jarvis command captured: \${commandObservationLabel(result)}"))
        assertTrue(wakeService.contains("JarvisConversationCommand.classify(question)"))
        assertTrue(wakeService.contains("JarvisConversationCommandType.TAKE_REST"))
        assertTrue(wakeService.contains("JarvisConversationCommandType.CONTINUE_PROMPT"))
        assertTrue(wakeService.contains("SESSION_CONTINUE_RESPONSE_TEXT"))
        assertTrue(wakeService.contains("SESSION_REST_RESPONSE_TEXT"))
        assertTrue(wakeService.contains("speakAndContinueConversation(speech"))
        assertTrue(wakeService.contains("transitionTo(JarvisConversationState.COMMAND_CAPTURE, \"conversation speech complete\")"))
        assertTrue(wakeService.contains("scheduleCommandStart(CONVERSATION_TURN_DELAY_MS)"))
        assertTrue(wakeService.contains("handleConversationNoMatch"))
        assertTrue(wakeService.contains("CONVERSATION_NO_MATCH_RELISTEN_MS"))
        assertTrue(wakeService.contains("MAX_EMPTY_CONVERSATION_LISTENS"))
        assertTrue(wakeService.contains("emptyListenCount"))
        assertTrue(wakeService.contains("Jarvis command recognition alternatives: count="))
        assertTrue(wakeService.contains("commandObservationLabel"))
        assertTrue(wakeService.contains("debugAlternativesLabel"))
        assertTrue(wakeService.contains("RecognizedCommandResult"))
        assertTrue(wakeService.contains("latestCommandPartial"))
        assertTrue(wakeService.contains("Using command partial after no-match"))
        assertTrue(wakeService.contains("handleCommandText(latestCommandPartialResult)"))
        assertTrue(wakeService.contains("failCommandCapture"))
        assertTrue(wakeService.contains("transitionTo(JarvisConversationState.RETURN_TO_IDLE, reason)"))
        assertTrue(wakeService.contains("Founder Brain voiceSummary received: chars="))
        assertTrue(wakeService.contains("RecognizerIntent.EXTRA_PREFER_OFFLINE, false"))
        assertTrue(wakeService.contains("RecognizerIntent.EXTRA_PARTIAL_RESULTS, isCommand || targetState == JarvisConversationState.IDLE"))
        assertTrue(wakeService.contains("RecognizerIntent.EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS"))
        assertTrue(wakeService.contains("selectBestCommandResult"))
        assertTrue(wakeService.contains("SpeechRecognizer.CONFIDENCE_SCORES"))
        assertTrue(wakeService.contains("RecognizedCommandCandidate"))
        assertFalse(wakeService.contains("firstOrNull()"))
        val onResults = wakeService.substringAfter("override fun onResults")
            .substringBefore("override fun onError")
        assertFalse(onResults.contains("restartListening"))
        assertTrue(onResults.contains("JarvisConversationState.IDLE"))
        assertTrue(onResults.contains("JarvisConversationState.COMMAND_CAPTURE"))
        assertTrue(onResults.contains("scheduleWakeRestart"))
        val onError = wakeService.substringAfter("override fun onError")
            .substringBefore("override fun onEvent")
        assertFalse(onError.contains("restartListening"))
        assertTrue(onError.contains("JarvisConversationState.IDLE"))
        assertTrue(onError.contains("JarvisConversationState.COMMAND_CAPTURE"))
        assertTrue(onError.contains("scheduleWakeRestart"))
        assertTrue(wakeService.contains("Foreground service lifecycle: onCreate"))
        assertTrue(wakeService.contains("Foreground service lifecycle: onStartCommand"))
        assertTrue(wakeService.contains("Foreground service lifecycle: onDestroy"))
        assertTrue(wakeService.contains("SpeechRecognizer start"))
        assertTrue(wakeService.contains("SpeechRecognizer stop"))
        assertTrue(wakeService.contains("AudioRecord start"))
        assertTrue(wakeService.contains("AudioRecord stop"))
        assertTrue(wakeService.contains("purpose=wake-fallback"))
        assertTrue(wakeService.contains("purpose=command"))
        assertFalse(wakeService.contains("Audio focus requested"))
        assertFalse(wakeService.contains("Founder Brain is not connected"))
        assertFalse(wakeService.contains("Founder Brain is unavailable right now."))
        assertFalse(wakeService.contains("speaker?.speak(reason)"))
        assertFalse(wakeService.contains("speaker?.speak(answer.summary)"))
        assertTrue(connector.contains("val voiceSummary = json.optString(\"voiceSummary\").trim()"))
        assertTrue(connector.contains("missing required voiceSummary"))
        assertTrue(connector.contains("JarvisBrainSpeechPolicy.SAFE_FALLBACK_MESSAGE"))
        assertTrue(connector.contains("Founder Brain request started"))
        assertTrue(connector.contains("Founder Brain response received after"))
        assertTrue(connector.contains(".put(\"sessionId\", sessionId)"))
        assertTrue(connector.contains(".addHeader(\"X-Aritenis-Session-Id\", sessionId)"))
        assertTrue(connector.contains("fun isReady()"))
        assertTrue(speechPolicy.contains("answer.voiceSummary.trim()"))
        assertFalse(speechPolicy.contains("answer.summary"))
        assertTrue(speechPolicy.contains("SAFE_FALLBACK_MESSAGE"))
        assertTrue(speechPolicy.contains("route confidence"))
        assertTrue(speaker.contains("@Synchronized"))
        assertTrue(speaker.contains("engine.stop()"))
    }

    @Test
    fun porcupineWakeUsesOnDeviceJarvisKeywordWhenConfigured() {
        val buildGradle = sourceFile("app/build.gradle.kts").readText()
        val config = sourceFile("app/src/main/java/com/example/mykeyboard/personal/PersonalJarvisConfig.kt").readText()
        val porcupine = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisPorcupineWakeEngine.kt").readText()

        assertTrue(buildGradle.contains("PICOVOICE_ACCESS_KEY"))
        assertTrue(buildGradle.contains("ARITENIS_PICOVOICE_ACCESS_KEY"))
        assertTrue(buildGradle.contains("PICOVOICE_ACCESS_KEY"))
        assertTrue(buildGradle.contains("ai.picovoice:porcupine-android:4.0.0"))
        assertTrue(buildGradle.contains("com.alphacephei:vosk-android:0.3.75"))
        assertTrue(config.contains("fun picovoiceAccessKey()"))
        assertTrue(porcupine.contains("PorcupineManager.Builder()"))
        assertTrue(porcupine.contains(".setAccessKey(PersonalJarvisConfig.picovoiceAccessKey())"))
        assertTrue(porcupine.contains(".setKeyword(Porcupine.BuiltInKeyword.JARVIS)"))
        assertTrue(porcupine.contains("activeManager.start()"))
        assertTrue(porcupine.contains("manager?.stop()"))
        assertTrue(porcupine.contains("manager?.delete()"))
        assertFalse(porcupine.contains("SpeechRecognizer"))
        assertFalse(porcupine.contains("FounderBrain"))
        assertFalse(porcupine.contains("JarvisBrainConnector"))
    }

    @Test
    fun voskWakeUsesOfflineGrammarBeforeSpeechRecognizerFallback() {
        val buildGradle = sourceFile("app/build.gradle.kts").readText()
        val wakeService = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisWakeWordService.kt").readText()
        val vosk = sourceFile("app/src/main/java/com/example/mykeyboard/personal/JarvisVoskWakeEngine.kt").readText()

        assertTrue(buildGradle.contains("com.alphacephei:vosk-android:0.3.75"))
        assertTrue(wakeService.indexOf("porcupineWakeEngine?.start() == true") < wakeService.indexOf("voskWakeEngine?.start() == true"))
        assertTrue(wakeService.indexOf("voskWakeEngine?.start() == true") < wakeService.indexOf("purpose=wake-fallback"))
        assertTrue(vosk.contains("StorageService.unpack"))
        assertTrue(vosk.contains("vosk-model-small-en-us-0.15"))
        assertTrue(vosk.contains("Recognizer(activeModel, SAMPLE_RATE, WAKE_GRAMMAR)"))
        assertTrue(vosk.contains("SpeechService(recognizer, SAMPLE_RATE)"))
        assertTrue(vosk.contains("Vosk wake started: grammar=hey jarvis"))
        assertTrue(vosk.contains("wakeDelivered"))
        assertTrue(vosk.contains("if (!isStarted || wakeDelivered) return"))
        assertTrue(vosk.contains("if (text == UNKNOWN_TOKEN) return"))
        assertTrue(vosk.contains("JarvisWakeWordDetector.evaluate(text)"))
        assertTrue(vosk.contains("val accepted = decision.accepted && source != \"partial\""))
        assertTrue(vosk.contains("complete wake phrase ignored until final wake result"))
        assertTrue(vosk.contains("FALSE_WAKE"))
        assertTrue(vosk.contains("REAL_WAKE"))
        assertTrue(vosk.contains("\\\"hey jarvis\\\""))
        assertTrue(vosk.contains("\\\"[unk]\\\""))
        assertFalse(vosk.contains("FOUNDER_BRAIN"))
        assertFalse(vosk.contains("JarvisBrainConnector"))
    }

    private fun sourceFile(relativePath: String): File {
        val current = File("").absoluteFile
        val direct = File(current, relativePath)
        if (direct.exists()) return direct
        return File(current.parentFile, relativePath)
    }

    private fun sourceFiles(relativePath: String): List<File> {
        val dir = sourceFile(relativePath)
        return dir.walkTopDown().filter { it.isFile && it.extension == "kt" }.toList()
    }
}
